# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

btm <- function(biterms, x, K, W, alpha, beta, iter, win = 15L, background = FALSE, trace = 0L, check_convergence = 0L, convergence_tol = 0.001) {
    .Call('_BTM_btm', PACKAGE = 'BTM', biterms, x, K, W, alpha, beta, iter, win, background, trace, check_convergence, convergence_tol)
}

btm_infer <- function(model, x, type) {
    .Call('_BTM_btm_infer', PACKAGE = 'BTM', model, x, type)
}

btm_biterms <- function(btm_model) {
    .Call('_BTM_btm_biterms', PACKAGE = 'BTM', btm_model)
}

btm_biterms_text <- function(x, W, win = 15L) {
    .Call('_BTM_btm_biterms_text', PACKAGE = 'BTM', x, W, win)
}

ibtm <- function(biterms, x, K, W, a, b, iter, win = 15L, n_rej = 20L, trace = 0L, check_convergence = 0L, convergence_tol = 0.001, background = FALSE) {
    .Call('_BTM_ibtm', PACKAGE = 'BTM', biterms, x, K, W, a, b, iter, win, n_rej, trace, check_convergence, convergence_tol, background)
}

ibtm_biterms <- function(model) {
    .Call('_BTM_ibtm_biterms', PACKAGE = 'BTM', model)
}

obtm <- function(biterms, x, K, W, a, b, iter, win = 15L, lam = 1, n_part = 10L, trace = 0L, check_convergence = 0L, convergence_tol = 0.001, background = FALSE) {
    .Call('_BTM_obtm', PACKAGE = 'BTM', biterms, x, K, W, a, b, iter, win, lam, n_part, trace, check_convergence, convergence_tol, background)
}

obtm_biterms <- function(model) {
    .Call('_BTM_obtm_biterms', PACKAGE = 'BTM', model)
}

